spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JavaWeb?useUnicode=treu&characterEncoding=UTF-8
    username: root
    password: liyangLY
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      format_sql:true

