spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JavaWeb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: liyangLY
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.kawyang.entity